server:
  port: 10086
spring:
  application:
    name: eureka-register
eureka:
  instance:
    hostname: localhost
  client:
    fetch_registry: true
    register_with_eureka: true
    eviction_interval_timer_in_ms: 2000  #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    enable_self_preservation: false #禁用自我保护模式  （所谓自我保护模式，就是当EurekaServer节点在短时间内丢失过多客户端时，认为是网络故障引起的，从而暂不移除这些微服务的注册信息）
    service-url:
      defaultZone: http://localhost:10086/eureka/