server:
  port: 3450

# datasoure默认使用JDBC
spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.22.242.20:3357/witeye_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: softcan
      hikari:
          minimum-idle: 1
          maximum-pool-size: 15
          auto-commit: true
          idle-timeout: 30000
          pool-name: DatebookHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.22.242.20:3357/witeye_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: softcan
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

ignore:
  urls:
    - /authentication/**
    - /**/*.css
    - /social
    - /signin
    - /admin/smsCode
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
    - /wechat/token
    - /external/token
    - /api/file/imageFile
    - /phonePassword/token
    - /phonePassword/phoneRegister
    - /admin/user/codeAndPhoneRegister
    - /admin/user/codeRegister
    - /admin/user/phoneRegister
    - /httpserver/deviceapi/*
    - /api/f/api/h5/v2/police/addressInfo
    - /api/sysdict/v3/sysEnum
    - /api/smartlife/sync