server:
  port: 8102

threadPool:
  corePoolSize: 10
  maxPoolSize: 100
  queueCapacity: 10
  waitForTasksToCompleteOnShutdown: true
  awaitTerminationSeconds: 60
  threadNamePrefix: aieye-

spring:
    datasource:
        name: mysql_aieye
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://172.22.241.138:3357/mock-zsts?useUnicode=true&characterEncoding=utf-8
          username: root
          password: Jffc3501
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    data:
        mongodb:
#         database: test
         uri: mongodb://devicerootus:deviceroot@172.22.241.55:27017/devicelog
## 该配置节点为独立的节点，如果将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cndrealty.tenderinservice.entity  # 注意：对应实体类的路径
logging:
  level:
    com.cndrealty.tenderinservice: debug
