server:
  port: 4000
#Redis cache 过期时间设置
redis:
  host: 172.22.241.55
  port: 6379
  password:
  cache:
    expiration: 3600

# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.22.242.20:3357/witeye_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      #url: jdbc:mysql://220.161.7.10:3357/aieye2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: softcan
#         driver-class-name: com.mysql.jdbc.Driver
#         url: jdbc:mysql://172.22.242.20:3357/witeye_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#         username: root
#         password: softcan

# 分库分表支持
#sharding:
#  jdbc:
#    defaultDataSourceName:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: jffc3501
#      jdbc-url: jdbc:mysql://172.22.241.55:3306/aieye_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    datasource:
#      names: ds
#      ds:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        username: root
#        password: jffc3501
#        jdbc-url: jdbc:mysql://172.22.241.55:3306/aieye_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    config:
#      sharding:
#        tables:
#          sys_log:
#            actual-data-nodes: ds.sys_log_${0..1}
#            table-strategy:
#              inline:
#                sharding-column: id
#                algorithm-expression: sys_log_${id % 2}
#            key-generator-column-name: id

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.cndrealty.admin.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
fdfs:
  file-host: http://127.0.0.1:22121/
  tracker-list:
    - 127.0.0.1:22122

miniAppid_ty: wxbddf1066c2c775e0
miniAppid_tw: wxd81d0a532e4d31d5
miniAppsecret_ty: 84385fa8f41decd95b5a6d2563161baf
miniAppsecret_tw: a26644d4d2b2b351a033fd4b4eabec0a
miniGrantType: authorization_code

logging:
  level:
    com: debug

# 七牛OSS 配置
# qiniu:
#  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
#  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
#  bucket: pigcloud
#  qiniuHost: http://p0hpm86wj.bkt.clouddn.com/
